DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name             VARCHAR                           NOT NULL,
    email            VARCHAR                           NOT NULL,
    password         VARCHAR                           NOT NULL,
    registered       TIMESTAMP           DEFAULT now() NOT NULL
);